package.json, src/models/eos.js, src/routes/Dashboard/Dashboard.js, src/routes/Dashboard/DashboardCountries.js, src/routes/Dashboard/DashboardProducers.js, src/routes/Dashboard/DashboardSidebar.js, src/theme/palette.js, yarn.lock
- Add view to display producers distribution by country
- yarn
- yarn start
- click "Reward distribution" from side menu
=> feature: add view to display producers distribution by country

package.json, src/models/eos.js, src/routes/Dashboard/Dashboard.js, src/routes/Dashboard/DashboardNodes.js, src/routes/Dashboard/DashboardProducers.js, src/routes/Dashboard/DashboardRewards.js, src/routes/Dashboard/DashboardSidebar.js, yarn.lock
- Calculate the expected reward for each producer
- yarn
- yarn start
- click "Producers" from side menu
=> feature: calculate expected rewards

package.json, src/components/ProducersChart.js, src/components/TransactionsChart.js, src/models/eos.js, src/routes/Dashboard/DashboardProducers.js, src/routes/Dashboard/DashboardRewards.js, yarn.lock
- Add chart to display producer schedule 
- Add EOS exchange rate
- yarn
- yarn start
- click "Producers" from side menu
=> chore: add new card for producer schedule

.env.example, src/config/eos.js, src/models/eos.js, src/routes/Dashboard/DashboardNodes.js
- Display node type
- Display producer info
- Add new env variables for exchange rate 
- Solves #25 #21 
- yarn
- yarn start
- click "Nodes distribution" from side menu
=> chore: add note type and producer info

src/components/TransactionsChart.js, src/config/eos.js, src/routes/Dashboard/DashboardNodes.js, src/routes/Dashboard/DashboardRewards.js
- Change marker color according to node type
- Filter nodes by type
- Filter nodes by producer
- Resolve #52
- Resolve #41 
- Resolve #40 
- Resolve #11  
- yarn
- yarn start
- click "Nodes distribution" from side menu
=> chore: allow filter nodes

kubernetes/webapp-deployment.yaml, kubernetes/webapp-service.yaml
=> Improve kubernetes configuration for production, including ssl

kubernetes/hapi-deployment.yaml, kubernetes/hapi-service.yaml, kubernetes/hasura-deployment.yaml, kubernetes/hasura-service.yaml, kubernetes/networkpolicy.yaml, kubernetes/postgres-deployment.yaml, kubernetes/postgres-service.yaml, kubernetes/wallet-deployment.yaml, kubernetes/wallet-service.yaml, scripts/build.sh, scripts/clean.sh, scripts/deploy.sh, wallet/config/config.ini
Create the initial k8s files and utility scripts for the deployment of the eosio-monitor in the Openstack kubernetes cluster.
=> Kubernetes deployment

.env.lacchain, docker-compose.yaml, webapp/Dockerfile, webapp/src/components/ProducerCard.js, webapp/src/components/ProducersChart.js, webapp/src/config/eos.config.js, webapp/src/routes/Dashboard/DashboardNodes.js, webapp/src/routes/Dashboard/DashboardProducers.js, webapp/yarn.lock
resolve #123 
resolve #124 
resolve #125
=> feature env configuration

kubernetes/lacchain/webapp-deployment.yaml, kubernetes/lacchain/webapp-service.yaml, scripts/build.sh, scripts/deploy.sh
=> Create CI/CD test

kubernetes/lacchain/webapp-deployment.yaml, kubernetes/lacchain/webapp-service.yaml, scripts/build.sh, scripts/deploy.sh
=> Create the lacchain deployment.

hapi/src/services/producer.service.js, webapp/src/components/AccountInfo.js
- Resolve issued found by codefactor
1. yarn lint
=> chore: resolve codefactor issues

.github/workflows/push-lacchain-environment.yaml
=> Create a new github workflow for the lacchain branch.

webapp/src/components/Sidebar.js, webapp/src/config/eos.config.js
Resolve a bug with mainnet network when the nodeTypes are missing 
1. make run mainnet
2. navigate to http://localhost:3000/dashboard/nodes
=> fix: missing node types

webapp/package.json, webapp/yarn.lock
=> fix: build error

scripts/build.sh
Update modules when there are changes to the Javascript code. (refs #170)
=> Fix the build proccess, update the node modules

webapp/src/routes/Nodes.js
- Change subscription by query to avoid multiple renders of SVG map
- Resolve #166 
2. navigate to http://localhost:3000/nodes
3. try to navigate between page
=> fix: app stuck after navigate

webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.lacchain.json
=> fix(i8n): adjust texts

hapi/src/services/producer.service.js, hapi/src/workers/producers.worker.js, webapp/src/components/NodeCard.js, webapp/src/components/NodeSearch.js, webapp/src/components/Tooltip.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.json, webapp/src/language/es.lacchain.json, webapp/src/routes/Lacchain/LacchainNodes.js, webapp/src/routes/Nodes.js, webapp/src/routes/index.js, webapp/src/theme/variants.js
- Add a new section with node list for lacchain
- Resolve #182
1. `make run lacchain`
2. navigate to http://localhost:3000/nodes
=> feat: new section with node list

webapp/src/components/Header.js, webapp/src/components/LacchainSetEntInfoField.js, webapp/src/components/LacchainSetNodeInfoActionInfoField.js, webapp/src/components/Sidebar.js, webapp/src/layouts/Dashboard.js, webapp/src/layouts/StandAlone.js, webapp/src/routes/Dashboard.js, webapp/src/routes/Lacchain/LacchainBoard.js, webapp/src/routes/Network.js, webapp/src/routes/NodesDistribution.js, webapp/src/routes/SmartContract.js, webapp/src/routes/index.js, webapp/src/utils/eos.js, webapp/src/utils/index.js, webapp/src/utils/lacchain.js
- Resolve #172
- Resolve #183
- Resolve #184
2. naviagtae to http://localhost:3000/nodes-distribution
3. check the filter options
=> fix nodes distribution 

webapp/src/language/en.lacchain.json, webapp/src/language/es.lacchain.json
- Resolve Add i18n values for form titles #201
1. log in as eosio account 
2. click on LACChain Management
3. form titles should be translated strings
=> add missing translations for lacchain management

hapi/src/services/producer.service.js, hasura/metadata/tables.yaml, makefile, webapp/src/components/AccountInfo.js, webapp/src/components/ContractActionForm.js, webapp/src/components/LacchainAddEntityActionEntityTypeField.js, webapp/src/components/LacchainSetEntInfoField.js, webapp/src/components/LacchainSetNodeInfoActionNodeField.js, webapp/src/components/NodeCard.js, webapp/src/components/NodeSearch.js, webapp/src/components/ProducerCard.js, webapp/src/components/ProducerSearch.js, webapp/src/components/ResourceUsage.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.json, webapp/src/language/es.lacchain.json, webapp/src/routes/Lacchain/LacchainBoard.js, webapp/src/routes/Network.js, webapp/src/routes/Producers.js, webapp/src/routes/Rewards.js, webapp/src/routes/SmartContract.js, webapp/src/routes/index.js, webapp/src/utils/on-img-error.js
- Resolve #199 
- Resolve #167 
- Resolve #198 
- Resolve #207 
- Resolve #197
- Resolve #164
- Resolve #165
- Resolve #202 
- Resolve #203
- Resolve #204
- Resolve #205
- Resolve #208
- Resolve #209 
- Resolve #210
- Resolve #214 
- Resolve #215 
2. navigate to http://localhost:3000/entities
=> fix: board issues

webapp/src/components/AccountInfo.js, webapp/src/components/ProducerSearch.js, webapp/src/routes/SmartContract.js
- Resolve #220
2. go http://localhost:3000/smart-contract
3. type an account name and hit enter
=> search on enter

webapp/src/components/NodeCard.js, webapp/src/components/NodeSearch.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/layouts/Dashboard.js, webapp/src/routes/BlockProducers.js, webapp/src/routes/Nodes.js
- Resolve #196 
- Resolve #235 
1. `make run jungle`
2. navigate to http://localhost:3000/nodes?owner=lion
=> feat: add url param to search nodes

scripts/build.sh
=> feat: optimize the docker builds by using stages.

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/index.js
=> fix: remove dashboard prefix from url

webapp/src/components/NodeCard.js
=> fix: missing endpoint for jungle and mainnet networks

webapp/src/components/NodeCard.js
- Resolve #N/A
1. first step
2. next step
=> chore: fix codefactor issues

webapp/src/routes/Home.js, webapp/src/routes/NetworkInfo.js
- Resolve #N/A
2. navigate to http://localhost:3000
=> fix: stuck home page with missing env variables

scripts/build.sh, scripts/clean.sh, webapp/Dockerfile
=> fix: add env variables to the webapp docker build.

webapp/src/config/eos.config.js, webapp/src/utils/eos.js
- Resolve #https://github.com/LatamLink/writer-middleware/issues/8
2. navigate to http://localhost:3000/lacchain/management
3. login with an entity account or eosio account
4. execute some transaction
=> fix signature error with privileged accounts

scripts/build.sh
=> fix: simplify the build script to make it easier to update.

webapp/src/language/es.lacchain.json, webapp/src/routes/Lacchain/LacchainManagement.js
- Resolve #279 
1. make run lacchain 
2. login with an entity account 
3. navigate to http://localhost:3000/lacchain/management
4. try to add a new node
=> feat: allow add nodes for entity accounts

webapp/src/components/ContractActionForm.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/layouts/Dashboard.js
- Resolve #276 
2. login with `eosio` account
3. navigate to http://localhost:3000/lacchain/management
4. fill the `Set net group` form
5. execute the transaction
=> fix: netsetgroup action data

kubernetes/hapi-deployment.yaml, kubernetes/hasura-deployment.yaml, kubernetes/lacchain/webapp-deployment.yaml, kubernetes/wallet-deployment.yaml
- added secret `regcred` wirth docker hub credentials
- use credentials for image pull to increase rate limit
=> fix(docker): add docker hub auths

kubernetes/hasura-deployment.yaml, kubernetes/wallet-deployment.yaml
=> fix: temporarily disable the pull of hasura and the wallet. refs #287

webapp/src/components/Header.js, webapp/src/language/en.json, webapp/src/language/es.json
- Resolve #211
- Resolve #180
2. navigate to http://localhost:3000/entities
=> feat: update header with login and logout actions

webapp/src/utils/lacchain.js
=> feat: add state history plugin option for nodes

webapp/src/components/LacchainSetEntInfoField.js
=> fix: allow an array for chain resource

webapp/src/components/NodeCard.js
- Resolve #294
2. navigate to http://localhost:3000/nodes
=> fix: blank screen for nodes pages

webapp/src/routes/Home.js
=> fix: empty logo for block producers

webapp/src/components/ContractActionForm.js
=> fix: invalid value [Object , Object] for input fields

webapp/src/routes/BlockProducers.js, webapp/src/routes/Nodes.js, webapp/src/routes/NodesDistribution.js
- Resolve #298
2. navigate to http://localhost:3000/nodes
=> feat: update pagination limit to 28

webapp/src/components/ContractActionForm.js, webapp/src/components/LacchainAddValidatorActionEntityField.js
- Resolve #273
3. login with eosio account
=> feat: add dropdown to select entity

webapp/src/components/ContractActionForm.js, webapp/src/components/LacchainAddValidatorActionEntityField.js, webapp/src/components/LacchainSetNodeInfoActionInfoField.js, webapp/src/components/LacchainSetScheduleActionValidatorsField.js, webapp/src/components/MultipleSelect.js, webapp/src/utils/lacchain.js
=> add multiple select input for validator schedule

kubernetes/wallet-statefulset.yaml, makefile
=> Add config volume to wallet container. 

makefile, webapp/package.json, webapp/src/components/ContractActionForm.js, webapp/src/components/EOSIONewAccountAuthority.js, webapp/src/language/en.lacchain.json, webapp/src/routes/Lacchain/LacchainManagement.js, webapp/src/utils/get-authority-template.js, webapp/yarn.lock
- Resolve #217 
- Resolve #218 
- Resolve #327
- Resolve #330 
1. make run
2. navigate http://localhost:3000/
=> feat: add new actions for permissioning committee and entity account

kubernetes/postgres-statefulset.yaml, kubernetes/storageclass.yml, kubernetes/wallet-statefulset.yaml
=> Configure a storageclass for the EOSIO dashboard

makefile, webapp/src/components/ContractActionForm.js, webapp/src/components/LacchainEntityField.js
- Resolve #328 
1. make run
3. login with a valid entity account
=> feat: fill entity for add node form

.github/workflows/push-lacchain-environment.yaml, .github/workflows/push-master-environment.yaml
workflow. refs #347
- Resolve #347
=> add 'REACT_APP_USE_CPU_BENCHMARK' to the container building action

hapi/src/services/producer.service.js, hasura/metadata/tables.yaml, hasura/migrations/1614745447025_alter_table_public_producer_add_column_health_status/down.sql, hasura/migrations/1614745447025_alter_table_public_producer_add_column_health_status/up.sql, webapp/public/config/boot.ini, webapp/public/config/observer.ini, webapp/public/config/validator.ini, webapp/public/config/writer.ini, webapp/src/components/NodeCard.js, webapp/src/components/ProducerCard.js, webapp/src/components/ProducerHealthIndicators.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/Lacchain/LacchainNodeConfig.js
- Resolve #186
2. navigate to http://localhost:3000/entities
3. check the new health status info
=> health status

webapp/src/components/LacchainSetNodeInfoActionInfoField.js
=> Remove extra p2p endpoint

.github/workflows/push-master-environment.yaml, webapp/makefile, webapp/src/components/ContractActionForm.js, webapp/src/components/LacchainAddNodeAuthorityField.js, webapp/src/components/LacchainSetNodeInfoActionInfoField.js
=> Update master 

.env.telostestnet, .gitignore, makefile, webapp/package.json, webapp/yarn.lock
- Resolve #367 
1. `make run telostestnet`
=> feat: add .env.telostestnet

.github/workflows/push-telos-environment.yaml, webapp/package.json, webapp/yarn.lock
Add GH Telos Work flow along with a minimal update of the eoscr-components package.
- closes #380 
We need to push some changes to the "telos" to test it.
=> feat: add telos workflow

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-master-environment.yaml, makefile
=> properly avoid statefulsets update errors on actions runs.

webapp/package.json, webapp/yarn.lock
=> refactor: update package version

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-master-environment.yaml, hapi/src/services/state-history-plugin.service.js
=> fix: missing env variables for kubernetes push files

webapp/src/components/TransactionsHistory.js, webapp/src/language/en.json, webapp/src/layouts/Dashboard.js, webapp/src/routes/Home.js
- Resolve #409 #385 
- Add Styles in order to allow breakpoints functionality
1. first step
2. next step
=> Card graphics refactor

hapi/src/services/producer.service.js, hasura/config.yaml, hasura/metadata/actions.yaml, hasura/metadata/tables.yaml, hasura/metadata/version.yaml, webapp/src/components/ContractActionForm.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/BlockDistribution.js, webapp/src/routes/EndpointsList.js, webapp/src/routes/index.js
- Resolve #260
- Resolve #408 
2. navigate to http://localhost:3000/endpoints
=> add endpoints report

hapi/src/services/stats.service.js, hasura/metadata/tables.yaml, hasura/migrations/1619390533943_alter_table_public_stat_add_column_nodes_summary/down.sql, hasura/migrations/1619390533943_alter_table_public_stat_add_column_nodes_summary/up.sql, webapp/src/components/NodesSummary.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.json, webapp/src/language/es.lacchain.json, webapp/src/routes/Home.js
- Resolve #423 
1. make run lacchain  
3. check the new cards
=> Nodes summary

webapp/src/components/InformationCard/index.js, webapp/src/components/InformationCard/styles.js, webapp/src/components/ProducerHealthIndicators.js, webapp/src/components/TransactionsLineChart.js, webapp/src/routes/BlockProducers.js, webapp/src/routes/Home/TransactionInfo.js, webapp/src/routes/NetworkInfo.js
- Resolve #384 
1. first step
2. next step
=> Use highchart instead of rechart, add card new UI

.github/workflows/push-lacchain-environment.yaml
`HAPI_EOS_STATE_HISTORY_PLUGIN_ENDPOINT: ''`
=> Hotfix for hapi service not starting

webapp/src/components/InformationCard/index.js
- Resolve code reviews changes
1. first step
2. next step
=> Use correct card title

kubernetes/webapp-deployment.yaml
Sometimes there is a mismatch between webapp version and container registry
=> Use latest tag for webapp image

hapi/src/services/state-history-plugin.service.js
=> chore(hapi): add logs for debug process

hapi/src/services/state-history-plugin.service.js
=> chore(hapi): rollback logs

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-master-environment.yaml, .github/workflows/push-telos-environment.yaml
- Resolve env variable issue
1. first step
2. next step
=> Add env variables values

hapi/src/services/state-history-plugin.service.js
=> fix(hapi): error on send message

webapp/src/components/Header.js, webapp/src/components/LacchainSetEntInfoField.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/EndpointsList.js, webapp/src/routes/Lacchain/LacchainManagement.js
- Resolve #428
- Resolve #426
3. login with an entity that doesn't have social media info 
3. navigate to http://localhost:3000/endpoints
4. try change the language
=> Fix missing social media inputs

webapp/src/components/NodesSummary.js, webapp/src/components/TransactionsHistory.js, webapp/src/routes/Home/BlockProducerInfo.js, webapp/src/routes/Home/TransactionInfo.js, webapp/src/routes/Home/index.js, webapp/src/routes/Home/styles.js
- Resolve new home page redesign
1. first step
2. next step
=> Card order in home page view

webapp/src/components/TransactionsLineChart.js, webapp/src/routes/BlockDistribution.js, webapp/src/routes/MissedBlocks.js
- Resolve #466 
1. run `make run lacchain`
2. test whole webapp and see the highchart graphs
=> Highchart license

webapp/yarn.lock
=> chore: update yarn.lock

webapp/package.json, webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.json, webapp/src/language/es.lacchain.json, webapp/src/routes/RicardianContract.js, webapp/yarn.lock
- Resolve #300 
1. run `make run lacchain`
2. go to `Block Producer Agreement`
=> Ricardian contract title

webapp/makefile
- Resolve N/A
2. navigate to http://localhost:3000
=> fix: wrong value for REACT_APP_DISABLED_MENU_ITEMS

webapp/src/components/InformationCard/Endpoints.js, webapp/src/components/InformationCard/Information.js, webapp/src/components/InformationCard/Media.js, webapp/src/components/InformationCard/Nodes.js, webapp/src/components/InformationCard/Social.js, webapp/src/components/InformationCard/index.js, webapp/src/components/InformationCard/styles.js, webapp/src/components/ProducerHealthIndicators.js, webapp/src/components/ProducerSocialLinks.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/BlockProducers.js, webapp/src/utils/formatData.js
- Resolve #453 #463 
1. run `make run lacchain`
2. go to entities and nodes pages in order to see information card
3. stop project `ctrl C and make stop`
4. run `make run mainnet`
5. see title on block producers information card
=> Re-order data on information cards

webapp/src/routes/Lacchain/LacchainManagement.js
- Resolve #485 
2. navigate http://localhost:3000/management
=> fix: missing node in lacchain management

docker-compose.yaml, hapi/Dockerfile, hapi/app.json, hapi/src/index.js
- Resolve #459
2. run `pm2 list`
=> feat(hapi): add debug tools

webapp/package.json, webapp/public/node-types/boot.svg, webapp/public/node-types/observer.svg, webapp/public/node-types/validator.svg, webapp/public/node-types/writer.svg, webapp/src/routes/Lacchain/LacchainNetwork.js, webapp/src/utils/lacchain.js, webapp/yarn.lock
- Resolve #494
1. first step
2. next step
=> fix(webapp): missing nodes for network topology

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-mainnet-environment.yaml, .github/workflows/push-telos-environment.yaml, kubernetes/webapp-deployment.yaml, utils/meta.mk, webapp/makefile
=> Compile different frontend for every different nework

.github/workflows/push-lacchain-environment.yaml
=> fix(lacchain): update graphql ingress host

.github/workflows/push-mainnet-environment.yaml
Greymass api seems to be down , lets switch back to using our own mainnet API
=> fix(mainnet): update mainnet api endpoint

.github/workflows/push-lacchain-environment.yaml
=> Update lacchain graphql endpoint

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-mainnet-environment.yaml, .github/workflows/push-telos-environment.yaml, webapp/makefile, webapp/src/config/general.js, webapp/src/language/en.json, webapp/src/routes/index.js
- resolves #394
- resolves #514 
- change telegram channel link
=> Fix version not updating

.github/workflows/push-telos-testnet-environment.yaml
=> Fix telos testnet workflow

hapi/src/services/stats.service.js
- Resolve #509
3. check the new card "TPS All Time High"
=> feat(hapi): improve tps all time high calculation

.github/workflows/push-proton-testnet-environment.yaml
=> Create proton testnet workflow

.env.jungle, .github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-mainnet-environment.yaml, .github/workflows/push-proton-testnet-environment.yaml, .github/workflows/push-telos-testnet-environment.yaml
- Add Proton and Telos testnets
- Adjust disabled menu items by network type
=> Adjust network menu items

webapp/src/components/InformationCard/Information.js, webapp/src/components/InformationCard/styles.js, webapp/src/components/ProducerSearch.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/BlockProducers.js, webapp/src/routes/Nodes.js, webapp/src/utils/formatData.js
- Resolve #261
- Resolve #527 
- Resolve #523 
- Resolve #528 
1. first step
2. next step
=> Add filter for other networks

docker-compose.yaml, hasura/Dockerfile, kubernetes/postgres-statefulset.yaml
=> Upgrade PostgresDB version 

hapi/src/services/stats.service.js, hasura/metadata/tables.yaml, hasura/migrations/1622180276502_alter_table_public_stat_add_column_unique_locations/down.sql, hasura/migrations/1622180276502_alter_table_public_stat_add_column_unique_locations/up.sql, webapp/src/components/TransactionsHistory.js, webapp/src/gql/producer.gql.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/models/eos.js, webapp/src/routes/Home/TransactionInfo.js
- Resolve #433
- Resolve #438 
3. check the new cards "Unique Locations" and "Daily Transactions"
=> feat: add unique locations and daily transactions

webapp/src/components/Authority.js, webapp/src/components/BlockSigningAuthority.js, webapp/src/components/ContractActionForm.js
- Resolve #556
3. fill the "Add Validator Node" form
4. click the "Execute transaction" button
5. confirm the node was added
=> fix(webapp): error on add ndoe

webapp/src/components/AccountInfo.js, webapp/src/components/ResourceUsage.js, webapp/src/routes/Home/BlockProducerInfo.js
- Resolve #563 
- Fix convert microseconds to milliseconds
- Add account mobile version
1. first step
2. next step
=> Add style to account contract and add responsive design

webapp/src/components/NodesSummary.js, webapp/src/components/TransactionsHistory.js, webapp/src/routes/Home/BlockProducerInfo.js
- Resolve #575 
1. first step
2. next step
=> Order cards by network

webapp/public/index.html, webapp/src/routes/Home/BlockProducerInfo.js
- Add Social image preview url
1. first step
2. next step
=> Change social image preview url

.github/workflows/push-lacchain-environment.yaml
=> fix(webapp): update lacchain footer links

hapi/src/services/stats.service.js, hapi/src/workers/producers.worker.js, hasura/metadata/tables.yaml, hasura/migrations/1623790281915_alter_table_public_stat_add_column_missed_blocks/down.sql, hasura/migrations/1623790281915_alter_table_public_stat_add_column_missed_blocks/up.sql, hasura/migrations/1624243573765_alter_table_public_stat_add_column_transaction_history/down.sql, hasura/migrations/1624243573765_alter_table_public_stat_add_column_transaction_history/up.sql, webapp/src/components/InformationCard/index.js, webapp/src/components/NodeSearch/index.js, webapp/src/components/NodeSearch/styles.js, webapp/src/components/ProducerSearch.js, webapp/src/gql/producer.gql.js, webapp/src/gql/transaction.gql.js, webapp/src/language/en.json, webapp/src/language/en.lacchain.json, webapp/src/language/es.json, webapp/src/language/es.lacchain.json, webapp/src/models/eos.js, webapp/src/routes/BlockProducers.js, webapp/src/routes/Home/TransactionInfo.js, webapp/src/routes/Nodes.js, webapp/src/utils/formatData.js
- Resolve #500 
- Resolve #589 
1. first step
2. next step
=> Refactor missed blocks

.github/workflows/push-dev-environment.yaml, .github/workflows/push-lacchain-environment.yaml, .github/workflows/push-mainnet-environment.yaml, .github/workflows/push-proton-testnet-environment.yaml, .github/workflows/push-telos-testnet-environment.yaml
=> Give a specific version to the kubernetes deployment github action

docs/index.html, docs/styles.css
=> Add initial hompage texts

docs/index.html, docs/styles.css
1. Clone branch.
2. Open index.html directly on browser.
=> Font and image resize

docs/index.html, docs/styles.css, hapi/src/services/stats.service.js, webapp/src/components/ProducersSummary.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/Home/BlockProducerInfo.js
- Resolve #106 
- Fix HTML W3C validations
1. first step
2. next step
=> Add time to finality logic and fix bugs

webapp/src/components/AccountInfo.js, webapp/src/components/ContractActionForm.js, webapp/src/components/InformationCard/index.js, webapp/src/components/ResourceUsage.js, webapp/src/routes/Home/BlockProducerInfo.js, webapp/src/routes/Lacchain/LacchainManagement.js, webapp/src/utils/formatData.js
- Resolve #592 
- Validate missed blocks array
1. first step
2. next step
=> Actions data

.github/workflows/push-wax-testnet-environment.yaml
=> add WAX testnet deployment

hapi/package.json, hapi/src/index.js, hapi/src/services/demux-state.service.js, hapi/src/services/demux/action-handler.js, hapi/src/services/demux/effects/index.js, hapi/src/services/demux/handler-version.js, hapi/src/services/demux/index.js, hapi/src/services/demux/updaters/eosio-setchedule.updater.js, hapi/src/services/demux/updaters/index.js, hapi/src/services/index.js, hapi/src/services/missed-blocks.service.js, hapi/src/services/state-history-plugin.service.js, hapi/src/workers/producers.worker.js, hapi/yarn.lock, hasura/metadata/tables.yaml, hasura/migrations/1625624719513_create_table_public_demux_state/down.sql, hasura/migrations/1625624719513_create_table_public_demux_state/up.sql, webapp/public/sitemap.proton-testnet.xml, webapp/public/sitemap.telos-testnet.xml, webapp/public/sitemap.telos.xml, webapp/public/sitemap.wax-testnet.xml, webapp/public/sitemap.wax.xml, webapp/src/routes/Accounts.js
- Resolve #613 
- Resolve #623 
- Resolve #621 
1. first step
2. next step
=> Missed blocks

hapi/src/services/demux-state.service.js, hapi/src/services/demux/action-handler.js, hasura/migrations/1625694525717_alter_table_public_demux_state_drop_column_block_number/down.sql, hasura/migrations/1625694525717_alter_table_public_demux_state_drop_column_block_number/up.sql, hasura/migrations/1625694558708_alter_table_public_demux_state_add_column_block_number/down.sql, hasura/migrations/1625694558708_alter_table_public_demux_state_add_column_block_number/up.sql, webapp/src/routes/Accounts.js, webapp/src/utils/get-transaction-url.js
- Resolve #598 
- Resolve #601 
- Resolve #500 
1. first step
2. next step
=> Missed block init values

webapp/src/components/NetworkSelector/index.js, webapp/src/components/NetworkSelector/styles.js, webapp/src/routes/Accounts.js
=> Fix network name space issue

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/layouts/Dashboard.js, webapp/src/layouts/styles.js
- Resolve #225 
1. first step
2. next step
=> Add logic to show description

hapi/src/services/demux/index.js
await for hasura before start demux
=> fix(hapi): await for hasura before start demux watch

.github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-lacchain.yaml, .github/workflows/deploy-mainnet.yaml, .github/workflows/deploy-proton-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml, .github/workflows/deploy-wax-testnet.yaml, .github/workflows/deploy-wax.yaml, docs/CNAME, docs/index.html, docs/styles.css, webapp/public/sitemap.proton-testnet.xml, webapp/public/sitemap.proton.xml
- Resolve #396 
- Resolve #582 
- Resolve #393
1. first step
2. next step
=> Update help texts and env vars

.github/workflows/deploy-mainnet.yaml
change `eos website` -> `eos community website`
=> Update footer links

docs/index.html, docs/styles.css, webapp/src/components/Header.js, webapp/src/layouts/Dashboard.js, webapp/src/layouts/styles.js
- Resolve #657
- Resolve #655
- Fix align dashboard header
- Align networks images and texts on lading page
=> Alignment issues

docker-compose.yaml
- Resolve #660
- Remove unnecessary code line
=> Remove unnecessary code line

webapp/src/utils/formatData.js
- Resolve #664 
2. navigate to http://localhost:3000/block-producers?name=eoscostarica
=> fix: missing ownership disclosure

webapp/src/components/ProducersChart.js, webapp/src/gql/producer.gql.js, webapp/src/routes/Home/BlockProducerInfo.js
- Resolve #670 
2. navigate http://localhost:3000/
=> fix: bp hover styles

webapp/src/language/en.json, webapp/src/language/es.json
- Resolve #686 
1. make run mainnet
3. confirm the new label it's there
=> fix: label

.env.proton, hapi/src/services/eosio.service.js, hapi/src/services/producer.service.js, hasura/metadata/tables.yaml, hasura/migrations/1632985720042_alter_table_public_producer_add_column_rank/down.sql, hasura/migrations/1632985720042_alter_table_public_producer_add_column_rank/up.sql, makefile, webapp/src/components/InformationCard/Stats.js, webapp/src/components/InformationCard/index.js, webapp/src/gql/producer.gql.js, webapp/src/routes/BlockProducers.js, webapp/src/utils/formatData.js
- Resolve #672 
1. make run proton
3. validate the producer data
=> fix: error with wrong label "Paid Standby" when user search

webapp/src/routes/BPJson.js
- Resolve #680 
2. navigate to http://localhost:3000/bpjson
3. login with producer account
4. check the bpjson data
=> feat: allow load bpjson data

webapp/src/components/ContractTables.js, webapp/src/components/MultipleSelect.js, webapp/src/components/ProducersChart.js, webapp/src/routes/Lacchain/LacchainNodeConfig.js
- Fix codefactor style issues
1. make run
=> fix(webapp): codefactor style issues

webapp/src/components/GeoMap/CountryMap.js, webapp/src/components/GeoMap/MainMap.js, webapp/src/components/GeoMap/styles.js, webapp/src/components/Tooltip.js, webapp/src/language/en.mainnet.json, webapp/src/language/en.proton-testnet.json, webapp/src/language/en.proton.json, webapp/src/language/en.telos-testnet.json, webapp/src/language/en.telos.json, webapp/src/language/en.wax-testnet.json, webapp/src/language/en.wax.json, webapp/src/language/es.mainnet.json, webapp/src/language/es.proton-testnet.json, webapp/src/language/es.proton.json, webapp/src/language/es.telos-testnet.json, webapp/src/language/es.telos.json, webapp/src/language/es.wax-testnet.json, webapp/src/language/es.wax.json, webapp/src/layouts/Dashboard.js
- Resolve #708 
- Resolve #704 
- Resolve #474 
1. first step
2. next step
=> (webapp): fix tooltip position and reward message

webapp/Dockerfile, webapp/yarn.lock
- Update webapp node version to 12.20.0
1. Check action ran complete without any error
=> fix(webapp): update node version

.github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-lacchain.yaml, .github/workflows/deploy-mainnet.yaml, .github/workflows/deploy-proton-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml, .github/workflows/deploy-wax-testnet.yaml, .github/workflows/deploy-wax.yaml
=> Update github actions.

.github/workflows/deploy-libre-testnet.yaml
=> add libre chain configuration

webapp/src/language/en.phoenix-testnet.json, webapp/src/language/es.phoenix-testnet.json
update phoenix i18n configuration
=> update phoenix i18n configuration

.github/workflows/deploy-airwire.yaml, webapp/src/language/en.airwire.json, webapp/src/language/es.airwire.json
=> feat(airwire): add airwire network

webapp/src/language/index.js
=> feat(airwire): add airwire i18n

kubernetes/airwire.ingress.yaml
=> Create a different ingress for airwire

.github/workflows/deploy-airwire-testnet.yaml, .github/workflows/deploy-airwire.yaml
=> fix typ0 in network links

.github/workflows/deploy-airwire-testnet.yaml
=> feat(cpumechanics): add cpu mechanics benchmarking

webapp/src/components/GeoMap/CountryMap.js, webapp/src/components/GeoMap/MainMap.js, webapp/src/components/GeoMap/index.js, webapp/src/components/Header.js, webapp/src/components/Header/index.js, webapp/src/components/Sidebar/index.js
- Resolve #722 
- Resolve #738 
1. run `make start`
2. go to `localhost:3000`
=> (webapp): compile warnings and airwire testnet

webapp/src/language/en.airwire-testnet.json, webapp/src/language/es.airwire-testnet.json, webapp/src/language/index.js
=> add airwire testnet language

.github/workflows/deploy-airwire-testnet.yaml
=> enable missed blocks

.github/workflows/deploy-airwire-testnet.yaml
=> fix graphql endpoint

.github/workflows/deploy-ultra-testnet.yaml
=> fix(ultra-testnet): update ingress route

.github/workflows/deploy-airwire-testnet.yaml
=> enable state history

kubernetes/configmap-dashboard.yaml, kubernetes/hapi-deployment.yaml
=> Add google credentials config map

kubernetes/configmap-dashboard.yaml
=> fix(hapi): update configmap

.github/workflows/deploy-ultra-testnet.yaml
=> remove ricardian contract for ultra-testnet

makefile, webapp/src/language/en.json, webapp/src/language/en.phoenix-testnet.json, webapp/src/language/es.json, webapp/src/language/es.phoenix-testnet.json, webapp/src/routes/Faucet.js, webapp/src/routes/index.js
- Implement UI for Phoenix
1. `make run <network>`
=> Feat/phoenix UI

.github/workflows/deploy-phoenix-testnet.yaml
=> fix(phoenix): update chainid

.github/workflows/deploy-phoenix-testnet.yaml
=> fix(phoenix): update chain ID

.github/workflows/deploy-airwire.yaml
=> Change airwire endpoint as requested by siliconswamp

hapi/src/utils/eos.util.js
- Resolve clean code
1. check empty space is removed
=> refactor(hapi): remove empty space

.github/workflows/deploy-libre-testnet.yaml
=> feat(libre): Update libre testnet chain ID

webapp/src/language/index.js
=> Fix Libre Mainnet Dashboard

.vscode/extensions.json, .vscode/settings.json
=> fix: Remove unused subdir

webapp/src/components/NetworkSelector/styles.js
=> fix(webapp): Fix ultra menu icon

webapp/yarn.lock
=> feat(webapp): Update dependencies

hapi/Dockerfile, webapp/Dockerfile
=> feat(webapp): Update Node version

hapi/yarn.lock, webapp/package.json, webapp/yarn.lock
- Update eoscr-components package
1. run `make start`
2. go to `localhost:3000`
=> (FE): update dependencies

webapp/src/routes/RewardsDistribution.js
- Fixes reference to map 404 error
=> Fix link to map resource

.github/workflows/deploy-libre-testnet.yaml
=> update chain id

hapi/yarn.lock, webapp/yarn.lock
=> update node dependencies

webapp/package.json, webapp/src/components/AccountInfo/index.js, webapp/src/components/BreakpointColumns/ColumnCreator.js, webapp/src/components/ContractTables/index.js, webapp/src/components/CountryFlag/index.js, webapp/src/components/InformationCard/Information.js, webapp/src/components/InformationCard/Nodes.js, webapp/src/components/InformationCard/Stats.js, webapp/src/components/LacchainAddEntityActionEntityTypeField/index.js, webapp/src/components/LacchainEntityField/index.js, webapp/src/routes/BlockDistribution/index.js, webapp/src/routes/CPUBenchmark/index.js, webapp/src/routes/Home/TransactionInfo.js, webapp/src/routes/Nodes/index.js, webapp/src/routes/RewardsDistribution/index.js, webapp/yarn.lock
- Optional chaining validations
1. first step
2. next step
=> (Package): optional chaining validations

webapp/src/config/general.js
- Resolve #825 
1. Enter jungle testnet and see dev branch
=> feat(frontend):updated dev branch

webapp/makefile
- Resolve #805 
1. Check the change
=> chore: remove unused build-arg

.github/workflows/deploy-libre.yaml, makefile
- Resolve #848 
1. Developer wise: make run libre
2. User wise: see footer change
=> chore: edit footer text and added libre in makefile

makefile
Libre Duplicated
1. See makefile
=> fix(makefile): Libre is duplicated

webapp/src/components/InformationCard/Information.js
- Resolve #868 
- Change validation of features, because the previous one is true for strings
1. check the change
=> Libre testnet node page was broken

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/About/index.js, webapp/src/routes/Help/index.js
- Resolve #904
1. Check the translation to spanish on about and help page
=> fix(About&Help): fix wrong language

webapp/src/components/Footer/index.js, webapp/src/components/Footer/styles.js
- Resolve #907 
1. run locally and click footer links
before, some parts of the footer were not visible on mobile, now they are
=> fix(footer): fixed links and fixed non responsive footer on mobile #907

webapp/src/components/Footer/styles.js, webapp/src/components/Header/styles.js, webapp/src/layouts/styles.js, webapp/src/routes/Home/styles.js
- Resolve #951 
1. See dashboard mainpage
=> chore(webapp): lighter shadows

webapp/src/components/Footer/index.js, webapp/src/components/Footer/styles.js, webapp/src/routes/Home/styles.js
- Resolve #947 
1. Open project
2. See footer on mobile
=> 947 mobile footer redesign

.github/workflows/codeql-analysis.yml
=> feat(github): Adds code scanning to repo

webapp/src/components/AccountInfo/styles.js, webapp/src/components/ContractTables/styles.js, webapp/src/context/snackbar-message.context.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/Accounts/index.js, webapp/src/routes/Accounts/styles.js
- Resolve #926
1. Go to accounts and contracts
2. Search by query parameters `account` and `table` at `http://localhost:3000/accounts?account=stake.libre&table=stake` and refresh or open in a new window to verify account doesnt reset to EOSIO.
By default, when account isnt entered `eosio` will be loaded by default
=> 926 account params not loading data

webapp/src/components/NetworkSelector/index.js, webapp/src/components/NetworkSelector/styles.js
- Resolve #986 
1. See network selector
=> 986 telos network selector

webapp/src/components/NetworkSelector/index.js
Removed box component on Network Selector
=> refactor(webapp): removed box component

.github/workflows/deploy-mainnet.yaml
=> fix(webapp): update EOS API

webapp/src/language/en.json
=> Update Help Text

.github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-wax.yaml
=> Update network labels

docs/index.html, docs/styles.css
- Resolve #998 
1. See desktop/mobile view
=> 998 add missing networks to homepage

hapi/src/services/eosio.service.js, hapi/src/services/producer.service.js
- Resolve #1007 
Showing first block producer for demonstration purposes:
=> fix(hapi): sync producers error

.env.protontestnet, hapi/src/routes/get-producers-info.route.js, hapi/src/routes/index.js, hapi/src/services/producer.service.js, hapi/src/workers/producers.worker.js, hasura/metadata/actions.graphql, hasura/metadata/actions.yaml, hasura/metadata/allow_list.yaml, hasura/metadata/databases/default/tables/public_endpoints_by_producer_id.yaml, hasura/metadata/databases/default/tables/public_producer.yaml, hasura/metadata/databases/default/tables/tables.yaml, hasura/metadata/query_collections.yaml, hasura/metadata/rest_endpoints.yaml, hasura/migrations/default/1666797367779_run_sql_migration/down.sql, hasura/migrations/default/1666797367779_run_sql_migration/up.sql
=> feat(hapi): created get-producers-info endpoint

hapi/src/services/producer.service.js
=> fix(hapi): edited where condition in get-producers-info endpoint

hapi/src/services/producer.service.js
=> fix(hapi): edited where condition in get-producers-info endpoint (#1022)

.github/workflows/deploy-mainnet.yaml
=> fix(mainnet): update API endpoint

webapp/src/language/es.json
=> chore(webapp): eos change to antelope

.github/workflows/deploy-mainnet.yaml
=> Update API endpoint

webapp/src/components/ProducersSummary/index.js, webapp/src/components/TransactionsHistory/index.js, webapp/src/routes/Home/BlockProducerInfo.js, webapp/src/routes/Home/styles.js, webapp/src/routes/RewardsDistribution/styles.js
Before
After
For issue #1010 
- Resolve #1021 #1010
=> fix(webapp): fixed transaction history view

webapp/src/routes/Home/styles.js, webapp/src/routes/RewardsDistribution/index.js, webapp/src/routes/RewardsDistribution/styles.js
- Resolve #1010 
Previous change seemed to not work correctly on dev branch, so another way was implemented
Before
After:
=> chore(webapp): matching cards and removed unused classes #1010

.github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-mainnet.yaml
=> Fix escape chars in HAPI_EOS_API_ENDPOINTS

webapp/src/components/RicardianContract/styles.js, webapp/src/routes/RicardianContract/index.js, webapp/src/routes/RicardianContract/styles.js
- Resolve #1011 
1. Navigate to Block Producer Agreement
=> feat(webapp): added container

webapp/src/components/Footer/index.js, webapp/src/components/Footer/styles.js, webapp/src/language/en.json, webapp/src/language/es.json
=> feat(webapp): added Edenia

.github/workflows/deploy-lacchain.yaml, .github/workflows/deploy-libre-testnet.yaml, .github/workflows/deploy-libre.yaml, .github/workflows/deploy-proton-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml, .github/workflows/deploy-ultra-testnet.yaml, .github/workflows/deploy-wax-testnet.yaml, .github/workflows/deploy-wax.yaml
=> Update env var syntax

.github/workflows/deploy-airwire-testnet.yaml, .github/workflows/deploy-airwire.yaml, .github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-lacchain.yaml, .github/workflows/deploy-libre-testnet.yaml, .github/workflows/deploy-libre.yaml, .github/workflows/deploy-mainnet.yaml, .github/workflows/deploy-proton-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml, .github/workflows/deploy-ultra-testnet.yaml, .github/workflows/deploy-wax-testnet.yaml, .github/workflows/deploy-wax.yaml
fix(devops): change versions on actions for deprecated issues
=> fix(devops): change versions for deprecated issues

.github/workflows/deploy-airwire-testnet.yaml, .github/workflows/deploy-airwire.yaml, .github/workflows/deploy-jungle-testnet.yaml, .github/workflows/deploy-lacchain.yaml, .github/workflows/deploy-libre-testnet.yaml, .github/workflows/deploy-libre.yaml, .github/workflows/deploy-mainnet.yaml, .github/workflows/deploy-proton-testnet.yaml, .github/workflows/deploy-proton.yaml, .github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml, .github/workflows/deploy-ultra-testnet.yaml, .github/workflows/deploy-wax-testnet.yaml, .github/workflows/deploy-wax.yaml
fix(devops): change versions for deprecated issues master
=> fix(devops): change versions for deprecated issues master

docker-compose.yaml, hasura/Dockerfile
- Update hasura version to fix critical security bug 
https://github.com/hasura/graphql-engine/releases/
=> update hasura version

hasura/metadata/databases/default/tables/public_endpoints_by_producer_id.yaml
- Resolve #1124 
- Add permissions to guest role to select data from endpoints_by_producer_id view 
1. Check the endpoints_by_producer_id view permissions.
=> Fix/data isn't shown

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/Accounts/useAccountState.js
- Resolve #1120
- The error message was incorrect, then an endpoints failure message was added.
2. Go to the "Accounts and Contracts" page.
3. Search for account that doesn't exists.
4. Check the error displayed.
5. Search for account that exists.
6. Check the account data.
_Show the account data_
_The account doesn't exists_
_The Endpoints used to request account data didn't respond_
=> feat(webapp): improve error message in Accounts and Contracts page

webapp/public/sitemap.jungle.xml, webapp/public/sitemap.libre-testnet.xml, webapp/public/sitemap.libre.xml, webapp/public/sitemap.mainnet.xml, webapp/public/sitemap.proton-testnet.xml, webapp/public/sitemap.proton.xml, webapp/public/sitemap.telos-testnet.xml, webapp/public/sitemap.telos.xml, webapp/public/sitemap.wax-testnet.xml, webapp/public/sitemap.wax.xml
- Resolve #1142
1. Check the date format in the sitemaps.
=> fix(webapp): fix invalid date in the sitemaps

webapp/src/language/en.json
=> Update undiscoverable bps sidebar text

webapp/src/language/en.json
=> Update accounts and contracts sidebar text

.github/workflows/deploy-libre.yaml
=> Enable cpu benchmarks for libre mainnet

.github/workflows/deploy-libre-testnet.yaml, .github/workflows/deploy-libre.yaml
=> Production Release

docs/index.html, docs/styles.css
=> Update homepage texts

.github/workflows/deploy-libre.yaml
=> Enable missed blocks on libre mainnet

hapi-evm/makefile
- Fix reference of wrong variable
=> fix(makefile): update container variable reference

hapi-evm/Dockerfile
=> fix(dockerfile): copy dist instead of src directory

.github/workflows/deploy-telos-testnet.yaml, .github/workflows/deploy-telos.yaml
- Change the port of the HASURA_GRAPHQL_ACTION_EVM_URL from 9090 to 9091
=> fix(workflows): fix wrong evm port

webapp/public/sitemap.libre-testnet.xml, webapp/public/sitemap.libre.xml, webapp/public/sitemap.telos-testnet.xml, webapp/public/sitemap.telos.xml
- Add evm pages in the sitemaps
- Update libre sitemaps
=> chore(webapp): update sitemaps and add telos evm routes

.github/workflows/deploy-proton.yaml
=> enable cpu benchmarks for proton mainnet

.github/workflows/deploy-jungle-testnet.yaml, webapp/public/sitemap.jungle.xml
=> Enable cpu benchmarks for jungle testnet

webapp/public/index.html, webapp/src/components/PageTitle/index.js, webapp/src/language/en.json, webapp/src/layouts/Dashboard.js
- Resolve #1296
2. Check the meta tags
=> feat(webapp): add separate meta description per page

webapp/public/index.html
Add meta tags for the default title and description
=> chore(webapp): add default meta description and twitter tags

docs/index.html, docs/styles.css
=> Fix home page html

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/About/index.js, webapp/src/routes/Help/index.js
- Resolve #1323 
- Resolve #1322
=> Improve help and about pages

webapp/public/sitemap.airwire-testnet.xml, webapp/public/sitemap.airwire.xml, webapp/public/sitemap.jungle.xml, webapp/public/sitemap.lacchain.xml, webapp/public/sitemap.libre-testnet.xml, webapp/public/sitemap.libre.xml, webapp/public/sitemap.mainnet.xml, webapp/public/sitemap.telos-testnet.xml, webapp/public/sitemap.telos.xml, webapp/public/sitemap.ultra-testnet.xml, webapp/public/sitemap.wax-testnet.xml, webapp/public/sitemap.wax.xml, webapp/public/sitemap.xpr-testnet.xml, webapp/public/sitemap.xpr.xml
=> fix(webapp): update sitemap lastmod

hapi/src/utils/producer.util.js
- Resolve #1372 
1. Run the project locally with Telos configuration
2. Go to 'Block Producers' page
3. Check the votes and rewards values
=> fix(hapi): fix votes and rewards of bps in telos

webapp/src/components/ChartHeader/styles.js, webapp/src/components/ProducersChart/index.js
- Resolve #1382
2. Check the chart in the main page
=> chore(webapp): set text color for producer names except the one producing

hasura/migrations/default/1701189064166_create_evm_stats_view_v5/up.sql
Reverts edenia/antelope-tools#1396
=> Revert "fix(hasura): fix evm stats view migration"

.github/workflows/deploy-fio-testnet.yaml
=> Adjust FIO Testnet Docker Image Tag
