webapp/src/language/en.lacchain.json, webapp/src/utils/eos.js
- Avoid use the actin run when the account it's `eosio`
1. make run lacchain 
2. login with `eosio` account
3. navigate to http://localhost:3000/lacchain/management
4. execute some transaction
=> chore: avoid add action run when the account it's eosio

webapp/.eslintrc, webapp/package.json, webapp/src/index.js, webapp/yarn.lock
Avoid load unused icons from ual-reactjs-renderer to reduce the final bundle size
for more information take a look to https://github.com/EOSIO/ual-reactjs-renderer/issues/103 and https://github.com/EOSIO/ual-reactjs-renderer/pull/105
3. check the loading time
=> reduce final bundle size 

webapp/src/components/TransactionsChart.js, webapp/src/components/TransactionsLineChart.js, webapp/src/language/en.json, webapp/src/models/eos.js, webapp/src/routes/Home.js
- Resolve #383 
1. run `make run lacchain`
2. go to localhost:3000
3. go to home and see transactions linear graphic
=> Refactor transaction graphics

hapi/src/utils/axios.util.js
Increase timeout to avoid empty bpJson
=> fix(hapi): increase timeout to avoid empty bpjson

hapi/src/services/eosio.service.js
=> fix: missing filter for active producers

hapi/src/services/eosio.service.js
- Resolve #665 
1. make run mainnet
3. take a look to eosauthority data
=> fix: missing data for eosauthority

webapp/src/routes/Faucet.js
- Improve error messages handling
1. `make run <network>`
=> feat(webapp): handle error messages in faucet

webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/BPJson.js
Created validation to verify consistency bpjson on chain vs off chain
Resolve #766
=> feat(webapp): validate consistency bpjson

.github/workflows/deploy-phoenix-testnet.yaml, .gitignore
=> fix(phoenix): update chain ID

.github/workflows/deploy-libre.yaml, webapp/src/language/en.libre.json, webapp/src/language/es.libre.json
=> Add libre mainnet instance

hapi/package.json, hapi/yarn.lock
- Resolve `@hapi/hapi:19.1.1` is not compatible with `node:16.16.0`
More on [official documentation](https://hapi.dev/resources/status/#hapi)
1. make run <network>
=> update(hapi): update @hapi/hapi to ^20.2.2

README.md
- Resolve #829
1. Check the content of the readme file
=> feat(readme): improve readme 829

webapp/src/routes/RewardsDistribution/index.js, webapp/src/routes/RewardsDistribution/styles.js
- Resolve #945 
1. Navigate to Rewards Distribution
=> 945 add padding and shadow to geomap tooltip

webapp/src/routes/RewardsDistribution/index.js, webapp/src/routes/RewardsDistribution/styles.js
- Resolve #956 
1. Navigate to Rewards distribution and see mobile view
=> fix(webapp): correct card dimensions for mobile

hasura/metadata/databases/default/tables/public_endpoint.yaml, hasura/metadata/databases/default/tables/public_node.yaml, hasura/metadata/databases/default/tables/public_node_info.yaml
- Resolve #966
1. Go to Hasura console
1. Check that the guest role has permissions to select node, node_info and endpoints tables
=> fix(hasura): add select permissions for guest role

webapp/src/components/GeoMap/styles.js, webapp/src/components/HealthCheck/styles.js, webapp/src/components/Tooltip/styles.js, webapp/src/routes/About/index.js, webapp/src/routes/About/styles.js, webapp/src/routes/BPJson/index.js, webapp/src/routes/BPJson/styles.js, webapp/src/routes/BlockProducers/index.js, webapp/src/routes/BlockProducers/styles.js, webapp/src/routes/EndpointsList/index.js, webapp/src/routes/EndpointsList/styles.js, webapp/src/routes/Help/index.js, webapp/src/routes/Help/styles.js, webapp/src/routes/Nodes/index.js, webapp/src/routes/Nodes/styles.js, webapp/src/routes/NodesDistribution/index.js, webapp/src/routes/NodesDistribution/styles.js
- Resolve #978 
1. Navigate to all pages
=> 978 add borders to all boxes

hapi/src/services/eosio.service.js, hapi/src/services/producer.service.js, hapi/src/utils/producer.util.js, hasura/metadata/databases/default/tables/public_producer.yaml, hasura/migrations/default/1674860295415_alter_table_public_producer_add_column_bp_json_url/down.sql, hasura/migrations/default/1674860295415_alter_table_public_producer_add_column_bp_json_url/up.sql, webapp/src/components/EndpointsTable/EndpointInfo.js, webapp/src/components/EndpointsTable/index.js, webapp/src/components/HealthCheck/HealthCheckInfo.js, webapp/src/components/InformationCard/EmptyState.js, webapp/src/components/InformationCard/index.js, webapp/src/components/NonCompliantCard/index.js, webapp/src/components/NonCompliantCard/styles.js, webapp/src/components/VisitSite/styles.js, webapp/src/gql/producer.gql.js, webapp/src/hooks/customHooks/useNonCompliantState.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/BPJson/useBPJsonState.js, webapp/src/routes/RewardsDistribution/RewardsDistributionStats.js, webapp/src/routes/RewardsDistribution/index.js
- Resolves #1131 
- Resolves #1132 
- Resolves #1135 
- Resolves #1136
- Use the right bp.json link in the Rewards Distribution.
- Remove zoom from Rewards Distribution map.
2. Go to "Block Producers" page.
3. Scroll down until you find an undiscoverable BP.
4. Click the link "View undiscoverable BPs list".
5. Check the status of the health check of the websites.
6. Check the bp.json url.
7. Click the link "BP JSON Generator".
8. Check the BP JSON Generator completes the candidate name and website.
**Link to undiscoverable BPs from empty state**
**Undiscoverable BPs improvements**
**Undiscoverable BPs improvements**
**Undiscoverable BPs website health check**
**Undiscoverable BPs website health check**
**Use the right bp.json link instead of the default**
=> Feat/improve undiscoverable BPs

webapp/src/components/NonCompliantCard/index.js, webapp/src/hooks/customHooks/useNonCompliantState.js, webapp/src/language/en.json, webapp/src/language/es.json, webapp/src/routes/NonCompliantBPs/RewardsStats.js, webapp/src/routes/NonCompliantBPs/styles.js, webapp/src/routes/RewardsDistribution/RewardsDistributionStats.js
- Resolve #1134 
- Fix infinite skeleton when there are no undiscoverable bps
2. Go to undiscoverable bps page.
3. Check the yearly rewards.
**Yearly Rewards**
**Width of 1820 px**
**Width of 1920 px**
**Before**
**After**
=> Yearly undiscoverable bps rewards 

webapp/src/context/state.context.js, webapp/src/utils/eosapi.js
- Resolve #1164
- Clear the timeout id when the promise ends.
- Increase the timeout.
2. Go to "Account and Contracts" page.
3. Check that the error doesn't appear.
=> fix(webapp): Endpoints fail in Account and Contracts page

webapp/src/components/ProducersChart/index.js, webapp/src/components/ProducersChart/styles.js, webapp/src/routes/Home/styles.js
- Resolve #1184 
- Show cards with the same height
2. Go to main page
3. Check the producer's chart
=> fix(webapp): increase the space between the name of the producers

.github/workflows/deploy-libre-testnet.yaml
- Remove HAPI_EOS_STATE_HISTORY_PLUGIN_ENDPOINT and disable Missed blocks and Blocks Distribution routes
=> chore(workflows): disable plugin history in libre-testnet

webapp/src/utils/eosapi.js
- Resolve #1261 
- Set the date offset to zero to fix the calculation that determines if the endpoint information is out of date, which was causing the error: `Each endpoint failed when trying to execute the function`
2. Go to main page
3. Check the data
=> fix(webapp): use UTC to check if endpoint is outdated

webapp/nginx.conf
- Reduce the amount of time that css and js files are considered fresh to try to solve the problem of loading an old version of the app from the cache
=> chore(webapp): reduce the expiration of css and js files to seven days

webapp/src/components/ContractTables/index.js, webapp/src/components/Header/index.js, webapp/src/language/es.lacchain.json, webapp/src/layouts/Dashboard.js, webapp/src/routes/index.js
- Resolve #1326
- Resolve #1335 
2. Go to Accounts & Contracts or BP JSON Generator Page and see the button
3. Go to another page and see that the button does not appear.
=> chore(webapp): include the connect wallet button only on necessary pages

webapp/src/gql/producer.gql.js, webapp/src/hooks/customHooks/useEndpointsState.js, webapp/src/hooks/customHooks/useNodeState.js, webapp/src/hooks/customHooks/useSearchState.js, webapp/src/utils/is-same-object.js
- Resolve #1383
- Use the onSubscriptionData instead of data object
- When the page loads queries the data and uses it in case the subscription is not available
2. Go to nodes or endpoints page
=> fix(webapp): improve page load speed for endpoints page

hasura/migrations/default/1701189064166_create_evm_stats_view_v5/up.sql
- Add drop view if exists command to migration
=> fix(hasura): fix evm stats view migration

hasura/migrations/default/1701711193753_create_evm_stats_view_v5/down.sql, hasura/migrations/default/1701711193753_create_evm_stats_view_v5/up.sql, webapp/src/routes/EVMDashboard/index.js
- Remove the last migration and regenerate it, including the statement to drop the view if it exists 
2. Go to hasura console
3. Check the query from evm.stats view
=> fix(hasura): regenerate migration to get a partial ATH

webapp/src/layouts/Dashboard.js
- Resolve #1403
2. Go to an block producer profile
3. Use the developer tools to simulate a slow connection
4. Check the page title never is /block-producers/bpName>title
=> fix(webapp): set page title only if it exists

webapp/src/components/GeoMap/CountryMap.js, webapp/src/components/ProducersChart/index.js, webapp/src/gql/producer.gql.js, webapp/src/hooks/customHooks/useEndpointsState.js, webapp/src/routes/ProducerProfile/ProfileCard.js
1. Run the project locally using FIO configuration
2. Check the chart of the producers and BP profile pages
=> feat(webapp): display fio address instead of owner value

hasura/metadata/databases/default/tables/public_producer.yaml, hasura/metadata/databases/default/tables/public_stat.yaml
=> Update new atributes guest perms

.github/workflows/deploy-fio.yaml
=> Update FIO Mainnet workflow
